wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.15
    start_time: 1674141466.446373
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.8.15
      5: 0.13.9
      6: 4.24.0
      8:
      - 2
      - 3
      - 5
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.01
