timeout: "2h"
steps:
   - name: 'gcr.io/cloud-builders/docker'
     args: ['build', '-t', 'gcr.io/main-catwalk-374308/detox_app', '--file', './simple_app.dockerfile', '.']
   - name: 'gcr.io/cloud-builders/docker'
     args: ['push', 'gcr.io/main-catwalk-374308/detox_app']
   - name: 'gcr.io/cloud-builders/docker'
     args: ['build', '-t', 'gcr.io/main-catwalk-374308/detox_v1', '--file', './TrainerLocal.dockerfile', '.']
   - name: 'gcr.io/cloud-builders/docker'
     args: ['push', 'gcr.io/main-catwalk-374308/detox_v1']
options:
  machineType: 'N1_HIGHCPU_8'