wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1673208144.843611
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.15
      5: 0.13.7
      8:
      - 5
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.026356504593152863
