datapaths: ["../../../data/processed/balanced_tokens_test_n2000_l32.pt",
            "../../../data/processed/balanced_binary_labels_test_n2000.pt"]
modelpath: "../../../models/detox_checkpoint_binary.pth"
batch_size: 8
