datapaths: ["../../../data/processed/input_train_n1000_l32.pt",
          "../../../data/processed/labels_train_n1000.pt",
          "../../../data/processed/input_test_n500.pt",
          "../../../data/processed/labels_test_n500.pt"]
pretrained_name: "bert-base-uncased"
lr: 0.001
n_epochs: 1
batch_size: 16
