datapaths: ["../../../data/processed/balanced_tokens_train_n8000_l32.pt",
          "../../../data/processed/balanced_binary_labels_train_n8000.pt",
          "../../../data/processed/balanced_tokens_test_n2000_l32.pt",
          "../../../data/processed/balanced_binary_labels_test_n2000.pt"]
modelpath: "../../../models/detox_checkpoint_binary.pth"
pretrained_name: "bert-base-uncased"
lr: 0.001
n_epochs: 10 
batch_size: 32
