datapaths: ["../../../data/processed/tokens_train_n5000_l32.pt",
          "../../../data/processed/labels_train_n5000.pt",
          "../../../data/processed/tokens_test_n500_l32.pt",
          "../../../data/processed/labels_test_n500.pt"]
modelpath: "../../../models/detox_checkpoint1.pth"
pretrained_name: "bert-base-uncased"
lr: 0.001
n_epochs: 2 
batch_size: 32
